#!/usr/bin/env bash
# Language-agnostic habitat check plus this project's deterministic gates.
#
# Generated by /superpowers-init. Run locally or from CI:
#   bash scripts/ai-literacy-check.sh

set -euo pipefail

if [ ! -f HARNESS.md ]; then
  echo "[habitat] No HARNESS.md found — skipping"
  exit 0
fi

echo "[habitat] Checking project harness constraints..."

echo "[habitat] Constraint: Consistent formatting"
unformatted=$(gofmt -l .)
if [ -n "$unformatted" ]; then
  echo "gofmt would change:"
  echo "$unformatted"
  exit 1
fi

echo "[habitat] Constraint: Tests must pass"
go test ./...

if command -v gitleaks >/dev/null 2>&1; then
  echo "[habitat] Constraint: No secrets in source"
  gitleaks detect --source . --no-banner --exit-code 1
else
  echo "[habitat] gitleaks not on PATH — skip secrets scan"
fi

echo "[habitat] All local deterministic checks passed. See HARNESS.md."
